@include('layouts.partials.offcanvas.quick-notifications')
@include('layouts.partials.offcanvas.quick-actions')
@include('layouts.partials.offcanvas.quick-user')
@include('layouts.partials.offcanvas.quick-panel')
@include('layouts.partials.offcanvas.chat')
@include('layouts.partials.offcanvas.scrolltop')
@include('layouts.partials.offcanvas.toolbar')
